export const GET_MOVIES_STARTED = 'GET_MOVIES_STARTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_EXISTED_MOVIE_SUCCESS = 'GET_EXISTED_MOVIE_SUCCESS';
export const GET_EXISTED_CAST_SUCCESS = 'GET_EXISTED_CAST_SUCCESS';
export const GET_CAST_SUCCESS = 'GET_CAST_SUCCESS';
export const SET_COMPARE = 'SET_COMPARE';
export const SET_COMPARED_ID = 'SET_COMPARED_ID';
export const CLEAR_COMPARED_MOVIES = 'CLEAR_COMPARED_MOVIES';
export const REMOVE_COMPARED_MOVIE = 'REMOVE_COMPARED_MOVIE';
export const GET_MOVIE_STARTED = 'GET_MOVIE_STARTED';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';
export const SET_ACTIVE_TRUE = 'SET_ACTIVE_TRUE';
export const SET_ACTIVE_FALSE = 'SET_ACTIVE_FALSE';

